project_id = "dkqzzypemdewomxrjftv"

[functions.contact-form]
verify_jwt = false

[functions.convert-base64]
verify_jwt = false

[functions.elevenlabs-websocket]
verify_jwt = false

[functions.get-elevenlabs-signed-url]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.send-project-request]
verify_jwt = false

[functions.widget-script]
verify_jwt = false

[functions.check-low-credits]
verify_jwt = false

# Cron job para processar alertas de créditos baixos a cada 5 minutos
[[edge_runtime.schedulers]]
name = "check-low-credits-scheduler"
cron = "*/5 * * * *"
path = "/check-low-credits"